# frozen_string_literal: true

# HeliosLite — canonical `helioslite` formula.
#
# This installs prebuilt release binaries rather than building from source.
# The workspace depends on the `PhenoShared` git repository, so a source build
# would need a full Rust toolchain plus network access to an unrelated private
# repo, for a CLI that every supported platform already ships prebuilt.
#
# `packaging/homebrew/helioslite.rb` is regenerated by
# `.github/workflows/update-distribution.yml` on every release, which injects
# the real `sha256` values from the attached `.sha256` assets. Do not hand-edit
# the digests: an unreplaced placeholder yields an uninstallable formula.
class Helioslite < Formula
  desc "AI coding agent CLI — HeliosLite, the KooshaPari fork of tailcallhq/forgecode"
  homepage "https://github.com/KooshaPari/HeliosLite"
  version "2.13.21-h.0.2.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/KooshaPari/HeliosLite/releases/download/v#{version}/forge-x86_64-apple-darwin"
      sha256 "318fb6eff8eae19402a46df92270cffe5f55163d9d0c06dfece5966acb512b3f"
    else
      url "https://github.com/KooshaPari/HeliosLite/releases/download/v#{version}/forge-aarch64-apple-darwin"
      sha256 "4b26bfe8dfcadd371b8cb0d0d6709e67d5da7d048dffb7e0b2827eff1a954d10"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/KooshaPari/HeliosLite/releases/download/v#{version}/forge-x86_64-unknown-linux-gnu"
      sha256 "74e2209277cc703e4c1bcd5b07a2d1d0a2b0140a99fcd56dada7649335a33c6c"
    else
      url "https://github.com/KooshaPari/HeliosLite/releases/download/v#{version}/forge-aarch64-unknown-linux-gnu"
      sha256 "8c9c08a87b5155a03eb9176db2646ecc4708b0805e9c532e0f8ef72044b35a5b"
    end
  end

  # The storage daemon ships as a separate binary. It is a first-class part of
  # the install, not an optional add-on, so it is a `resource` rather than a
  # best-effort extra.
  resource "forge_dbd" do
    on_macos do
      if Hardware::CPU.intel?
        url "https://github.com/KooshaPari/HeliosLite/releases/download/v#{version}/forge_dbd-x86_64-apple-darwin"
        sha256 "983cfe304c7a6a807fb591c36a8dd95ccbf5253be62e464bc5bbf7585edea073"
      else
        url "https://github.com/KooshaPari/HeliosLite/releases/download/v#{version}/forge_dbd-aarch64-apple-darwin"
        sha256 "99b286e8c198ddb4ed3479c3528dea2e1bb97591b96180cde8eee3fc473ec31b"
      end
    end

    on_linux do
      if Hardware::CPU.intel?
        url "https://github.com/KooshaPari/HeliosLite/releases/download/v#{version}/forge_dbd-x86_64-unknown-linux-gnu"
        sha256 "8b2dd38cae7f7457672a67dd9c96e9e085df2278051d3144c597149bd8118e32"
      else
        url "https://github.com/KooshaPari/HeliosLite/releases/download/v#{version}/forge_dbd-aarch64-unknown-linux-gnu"
        sha256 "8ab4bb85b8a6c789f36d2049c86d783d8a2cbde0534a507ce19a707e390a12db"
      end
    end
  end

  def install
    # The release publishes one binary under both `forge-*` and `helioslite-*`
    # asset names. Install it once and expose the legacy name as a symlink so
    # the two can never drift across upgrades.
    bin.install Dir["forge-*"].first => "helioslite"
    bin.install_symlink "helioslite" => "forge"

    resource("forge_dbd").stage do
      bin.install Dir["forge_dbd-*"].first => "forge_dbd"
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/helioslite --version")
    assert_match version.to_s, shell_output("#{bin}/forge --version")
    # forge_dbd is versioned independently of the workspace, so only assert
    # that it executes rather than pinning it to the release tag.
    assert_match "forge_dbd", shell_output("#{bin}/forge_dbd --version")
  end
end
