# frozen_string_literal: true

# HeliosLite — canonical `helioslite` formula.
#
# This installs prebuilt release binaries rather than building from source.
# The workspace depends on the `PhenoShared` git repository, so a source build
# would need a full Rust toolchain plus network access to an unrelated private
# repo, for a CLI that every supported platform already ships prebuilt.
#
# `packaging/homebrew/helioslite.rb` is regenerated by
# `.github/workflows/update-distribution.yml` on every future release, which
# injects the real `sha256` values from the attached `.sha256` assets. Do not
# hand-edit the digests: an unreplaced placeholder yields an uninstallable
# formula. The v2.13.21-h.0.2.8 digests below were written by a manual run of
# that step (its release-triggered run raced the asset upload and failed; see
# the 45-minute retry fix in the workflow history).
class Helioslite < Formula
  desc "AI coding agent CLI — HeliosLite, the KooshaPari fork of tailcallhq/forgecode"
  homepage "https://github.com/KooshaPari/HeliosLite"
  version "2.13.21-h.0.2.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/KooshaPari/HeliosLite/releases/download/v#{version}/forge-x86_64-apple-darwin"
      sha256 "38c44310b96db7662535a1cca459a4f9ea0854d6b8c48a3e21ecbd76ee23571f"
    else
      url "https://github.com/KooshaPari/HeliosLite/releases/download/v#{version}/forge-aarch64-apple-darwin"
      sha256 "9814d4c3933681bf04a6abcf6c2f8086c88882f07644eb8c841cd05483c61cec"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/KooshaPari/HeliosLite/releases/download/v#{version}/forge-x86_64-unknown-linux-gnu"
      sha256 "84c5b8de6c5fa4feb786979f50778ad43a01b291985573d36dfa4ce6aed19a7f"
    else
      url "https://github.com/KooshaPari/HeliosLite/releases/download/v#{version}/forge-aarch64-unknown-linux-gnu"
      sha256 "eee360f9af23c93a083c464db315c21e9c39759663ca970317ef06f8aadac128"
    end
  end

  # The storage daemon ships as a separate binary. It is a first-class part of
  # the install, not an optional add-on, so it is a `resource` rather than a
  # best-effort extra.
  resource "forge_dbd" do
    on_macos do
      if Hardware::CPU.intel?
        url "https://github.com/KooshaPari/HeliosLite/releases/download/v#{version}/forge_dbd-x86_64-apple-darwin"
        sha256 "3c701e659a003bb15329949f31b826e23abd975f1150857bf69c07090fbf7094"
      else
        url "https://github.com/KooshaPari/HeliosLite/releases/download/v#{version}/forge_dbd-aarch64-apple-darwin"
        sha256 "572023ac46c7810f617966fed8bece0c560cc75711527693b5e05683c9f9f418"
      end
    end

    on_linux do
      if Hardware::CPU.intel?
        url "https://github.com/KooshaPari/HeliosLite/releases/download/v#{version}/forge_dbd-x86_64-unknown-linux-gnu"
        sha256 "8b2dd38cae7f7457672a67dd9c96e9e085df2278051d3144c597149bd8118e32"
      else
        url "https://github.com/KooshaPari/HeliosLite/releases/download/v#{version}/forge_dbd-aarch64-unknown-linux-gnu"
        sha256 "8ab4bb85b8a6c789f36d2049c86d783d8a2cbde0534a507ce19a707e390a12db"
      end
    end
  end

  def install
    # The release publishes one binary under both `forge-*` and `helioslite-*`
    # asset names. Install it once and expose the legacy name as a symlink so
    # the two can never drift across upgrades.
    bin.install Dir["forge-*"].first => "helioslite"
    bin.install_symlink "helioslite" => "forge"

    resource("forge_dbd").stage do
      bin.install Dir["forge_dbd-*"].first => "forge_dbd"
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/helioslite --version")
    assert_match version.to_s, shell_output("#{bin}/forge --version")
    # forge_dbd is versioned independently of the workspace, so only assert
    # that it executes rather than pinning it to the release tag.
    assert_match "forge_dbd", shell_output("#{bin}/forge_dbd --version")
  end
end
