# frozen_string_literal: true

# HeliosLite — canonical `helioslite` formula.
#
# This installs prebuilt release binaries rather than building from source.
# The workspace depends on the `PhenoShared` git repository, so a source build
# would need a full Rust toolchain plus network access to an unrelated private
# repo, for a CLI that every supported platform already ships prebuilt.
#
# `packaging/homebrew/helioslite.rb` is regenerated by
# `.github/workflows/update-distribution.yml` on every release, which injects
# the real `sha256` values from the attached `.sha256` assets. Do not hand-edit
# the digests: an unreplaced placeholder yields an uninstallable formula.
class Helioslite < Formula
  desc "AI coding agent CLI — HeliosLite, the KooshaPari fork of tailcallhq/forgecode"
  homepage "https://github.com/KooshaPari/HeliosLite"
  version "2.13.21-h.0.2.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/KooshaPari/HeliosLite/releases/download/v#{version}/forge-x86_64-apple-darwin"
      sha256 "7edf53e0ba2115ec16ecf6ffe9c317366438e9791037e087ff78681bbe26da20"
    else
      url "https://github.com/KooshaPari/HeliosLite/releases/download/v#{version}/forge-aarch64-apple-darwin"
      sha256 "4d1a9cf563bd062671795dded063e3ee452daab29f24c89db44e908d684972d1"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/KooshaPari/HeliosLite/releases/download/v#{version}/forge-x86_64-unknown-linux-gnu"
      sha256 "4f937cf3a34f623a6bd2f6c169acf2a5606e3bce5924c75b1dbe602f43c7c334"
    else
      url "https://github.com/KooshaPari/HeliosLite/releases/download/v#{version}/forge-aarch64-unknown-linux-gnu"
      sha256 "3e4a3a4fd001465489906934df948c06b4c68a987df07baa50711f4dac2ebf77"
    end
  end

  # The storage daemon ships as a separate binary. It is a first-class part of
  # the install, not an optional add-on, so it is a `resource` rather than a
  # best-effort extra.
  resource "forge_dbd" do
    on_macos do
      if Hardware::CPU.intel?
        url "https://github.com/KooshaPari/HeliosLite/releases/download/v#{version}/forge_dbd-x86_64-apple-darwin"
        sha256 "b2e7e8ec3ff97354502ad803252159e345407996928d464d40f9968cd419ff44"
      else
        url "https://github.com/KooshaPari/HeliosLite/releases/download/v#{version}/forge_dbd-aarch64-apple-darwin"
        sha256 "1442951ca4881e888778199bd7917a4022be12d30c5bd116037394c18252ebf3"
      end
    end

    on_linux do
      if Hardware::CPU.intel?
        url "https://github.com/KooshaPari/HeliosLite/releases/download/v#{version}/forge_dbd-x86_64-unknown-linux-gnu"
        sha256 "8b2dd38cae7f7457672a67dd9c96e9e085df2278051d3144c597149bd8118e32"
      else
        url "https://github.com/KooshaPari/HeliosLite/releases/download/v#{version}/forge_dbd-aarch64-unknown-linux-gnu"
        sha256 "8ab4bb85b8a6c789f36d2049c86d783d8a2cbde0534a507ce19a707e390a12db"
      end
    end
  end

  def install
    # The release publishes one binary under both `forge-*` and `helioslite-*`
    # asset names. Install it once and expose the legacy name as a symlink so
    # the two can never drift across upgrades.
    bin.install Dir["forge-*"].first => "helioslite"
    bin.install_symlink "helioslite" => "forge"

    resource("forge_dbd").stage do
      bin.install Dir["forge_dbd-*"].first => "forge_dbd"
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/helioslite --version")
    assert_match version.to_s, shell_output("#{bin}/forge --version")
    # forge_dbd is versioned independently of the workspace, so only assert
    # that it executes rather than pinning it to the release tag.
    assert_match "forge_dbd", shell_output("#{bin}/forge_dbd --version")
  end
end
